# Generated by Django 2.2.15 on 2020-08-27 16:42

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Region', '0002_auto_20200827_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your organization name', max_length=30, verbose_name='Org Name')),
                ('logo', models.ImageField(upload_to='images/logo/', verbose_name='Upload Your Logo')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Region.Address')),
            ],
        ),
    ]
