# Generated by Django 2.2.15 on 2020-08-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(choices=[('AYAR', 'Ayeyarwady'), ('BAGO', 'Bago Region'), ('CHIN', 'Chin State'), ('KCIN', 'Kachin State'), ('KYAH', 'Kayah State'), ('KYIN', 'Kayin State'), ('MGWY', 'Magway Region'), ('MDLY', 'Mandalay Region'), ('MONS', 'Mon State'), ('RKIN', 'Rakhine State'), ('SHAN', 'Shan State'), ('SAGI', 'Sagaing Region'), ('TNDY', 'Taninthary Region'), ('YGON', 'Yangon Region')], default='AYAR', max_length=4, verbose_name='Region/Division'),
        ),
    ]
